<a href="https://colab.research.google.com/github/diaszakir/ComputationalMathAssignment3/blob/main/Assignment3_DiasZakir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1: Iterative method for matrix inversion.
Problem:
1. Implement an iterative method to compute the inverse of matrix A
−1
. Use an initial guess B=1/tr(A) ⋅ I,
where tr(A) is the trace of the matrix. Set the accuracy to 10
−6
.
2. Matrix:

Required:
1. Print the resulting inverse matrix.
2. Compare the result with the built-in function numpy.linalg.inv.


In [ ]:
import numpy as np

def iterative_inverse(A, B, tol, max_iter):
    """Iterative method for finding the inverse matrix."""
    n = A.shape[0]
    I = np.eye(n)  # Unit matrix
    for _ in range(max_iter):
        E = np.dot(A, B) - I  # Calculating the error
        B_new = B - np.dot(B, E)  # Proximity update
        # Checking if we have achieved accuracy
        if np.linalg.norm(E, ord='fro') < tol:
            print(f"Converged after {_ + 1} iterations.")
            return B_new
        B = B_new
    return B_new

# Given matrix
A = np.array([[5, 2, 1], [2, 6, 3], [1, 3, 7]], dtype=float)
# Initial approximation
B = np.linalg.inv(A) + 0.1 * np.random.randn(3, 3)  # Noisy initial approximation

# Iterative process
A_inv = iterative_inverse(A, B, tol=1e-6, max_iter=100)
print("Inverse matrix (iteratively):")
print(A_inv)

A_inv_func = np.linalg.inv(A)
print("\nInverse matrix (numpy.linalg.inv):")
print(A_inv_func)

Converged after 9 iterations.
Inverse matrix (iteratively):
[[ 2.30769231e-01 -7.69230769e-02  1.68777867e-18]
 [-7.69230769e-02  2.37762238e-01 -9.09090909e-02]
 [ 5.57184175e-21 -9.09090909e-02  1.81818182e-01]]

Inverse matrix (numpy.linalg.inv):
[[ 0.23076923 -0.07692308  0.        ]
 [-0.07692308  0.23776224 -0.09090909]
 [ 0.         -0.09090909  0.18181818]]


Task 2: LU factorization and solution of a system of linear equations.
Problem:
1. Perform LU factorization of the matrix:
2. Using the result of the expansion, solve the system Ax=b, where:

Required:
1. Print matrices L and U.
2. Solve the system and print the x values.
3. Compare the result with the solution via numpy.linalg.solve.

In [ ]:
def lu_factorization(A):
    """LU factorization of a matrix."""
    n = A.shape[0]
    L = np.eye(n)  # Lower triangular matrix
    U = A.copy()  # Upper triangular matrix

    for i in range(n):
        for j in range(i+1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            U[j, i:] -= factor * U[i, i:]

    return L, U

def solve_lu(L, U, b):
    """Solving the system using LU decomposition."""
    # Straight move for Ly = b
    n = L.shape[0]
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])

    # Reverse move for Ux = y
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x

# Example of a matrix and right-hand side
A = np.array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]], dtype=float)
b = np.array([5, 20, -10, 15], dtype=float)

# LU-factorization
L, U = lu_factorization(A)

U[np.abs(U) < 1e-10] = 0
print("Lower triangular matrix L:")
print(L)
print("Upper triangular matrix U:")
print(U)

# Solution of the system
x = solve_lu(L, U, b)
print("Solution of Ax = b:")
print(x)

# Check
check = np.dot(A, x)
print("Check: A * x ≈ b")
print(check)

print("With built-in function")
sol_1 = np.linalg.solve(A, b)
print(sol_1)

Lower triangular matrix L:
[[ 1.          0.          0.          0.        ]
 [-0.1         1.          0.          0.        ]
 [ 0.2        -0.0733945   1.          0.        ]
 [ 0.          0.27522936 -0.08173077  1.        ]]
Upper triangular matrix U:
[[10.         -1.          2.          0.        ]
 [ 0.         10.9        -0.8         3.        ]
 [ 0.          0.          9.5412844  -0.77981651]
 [ 0.          0.          0.          7.11057692]]
Solution of Ax = b:
[ 0.82758621  1.48275862 -0.89655172  1.20689655]
Check: A * x ≈ b
[  5.  20. -10.  15.]
With built-in function
[ 0.82758621  1.48275862 -0.89655172  1.20689655]


Task 3: Finding the Largest Eigenvalue and Vector Using Power Method.
Problem:
1. Implement the power iteration method to find the largest eigenvalue and the corresponding
eigenvector.
2. Matrix:
3. Initial vector v0=[1,0,0].

Required:
1. Find the largest eigenvalue and vector.
2. Compare the result with the numpy.linalg.eig function.

In [ ]:
import numpy as np

def power_method(A, v0, tol, max_iter):
    v = v0 / np.linalg.norm(v0)  # Normalize the initial vector
    for _ in range(max_iter):
        w = np.dot(A, v)  # Matrix-vector multiplication
        lambda_new = np.dot(w, v)  # Eigenvalue approximation
        v_new = w / np.linalg.norm(w)  # Normalize the new vector

        # Convergence check
        if np.linalg.norm(v_new - v) < tol:
            return lambda_new, v_new

        v = v_new
    return lambda_new, v_new

# Example matrix
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]], dtype=float)
v0 = np.array([1, 0, 0], dtype=float)

# Finding the eigenvalue and vector
lambda_max, eigenvector = power_method(A, v0, tol=1e-6, max_iter=100)
print("Largest eigenvalue:", np.round(lambda_max, decimals=6))
print("The corresponding eigenvector:", eigenvector)
print("Answer of built-in function:")
e_values, e_vectors = np.linalg.eig(A)
print(e_values)

Largest eigenvalue: 3.414214
The corresponding eigenvector: [ 0.50000091 -0.70710678  0.49999909]
Answer of built-in function:
[3.41421356 2.         0.58578644]


Task 4: Comparison of Givens and Householder methods.
Problem:
1. Reduce the following matrix to upper triangular form using:
- Givens' method.
- Householder's method.

Required:
1. Derive the Q and R matrices for each method.
2. Compare the efficiency and numerical stability of the two methods

In [ ]:
def householder_qr(A):
    """QR decomposition by Householder method."""
    m, n = A.shape
    R = A.copy()
    Q = np.eye(m)

    for i in range(n):
        # Create a Householder vector
        x = R[i:, i]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        v = x - e
        v = v / np.linalg.norm(v)

        # Householder Matrix
        H = np.eye(m)
        H[i:, i:] -= 2.0 * np.outer(v, v)

        # Transformation of R and accumulation of Q
        R = H @ R
        Q = Q @ H.T

    return Q, R

def givens_rotation(A):
    """QR decomposition by Givens method."""
    m, n = A.shape
    Q = np.eye(m)  # Orthogonal matrix
    R = A.copy()

    for i in range(n):
        for j in range(i+1, m):
            if R[j, i] != 0:
                r = np.hypot(R[i, i], R[j, i])
                cos = R[i, i] / r
                sin = -R[j, i] / r

                G = np.eye(m)  # Givens rotation matrix
                G[i, i] = cos
                G[j, j] = cos
                G[i, j] = -sin
                G[j, i] = sin

                R = G @ R  # Transform R
                Q = Q @ G.T  # Accumulation of Q

    return Q, R

# Example
A = np.array([[4, 1, 2, 0], [1, 3, 1, 2], [2, 1, 5, 1], [0, 2, 1, 4]], dtype=float)

# QR decomposition
Q1, R1 = givens_rotation(A)
Q2, R2 = householder_qr(A)
Q1 = np.round(Q1, 2)
R1 = np.round(R1, 2)
Q2 = np.round(Q2, 2)
R2 = np.round(R2, 2)

print("Givens Method:")
print("Q:")
print(Q1)
print("R:")
print(R1)

print("\nHouseholder Method:")
print("Matrix Q:")
print(Q2)
print("Matrix R:")
print(R2)

# Check
print("Check: A ≈ QR")
print(np.round(Q1 @ R1, 2))
print()
print(np.round(Q2 @ R2))



Givens Method:
Q:
[[ 0.87 -0.21 -0.39  0.2 ]
 [ 0.22  0.77 -0.23 -0.56]
 [ 0.44  0.04  0.89 -0.13]
 [ 0.    0.6   0.09  0.8 ]]
R:
[[ 4.58  1.96  4.15  0.87]
 [ 0.    3.34  1.16  3.98]
 [ 0.    0.    3.53  0.79]
 [ 0.   -0.    0.    1.94]]

Householder Method:
Matrix Q:
[[ 0.87 -0.21 -0.39  0.2 ]
 [ 0.22  0.77 -0.23 -0.56]
 [ 0.44  0.04  0.89 -0.13]
 [ 0.    0.6   0.09  0.8 ]]
Matrix R:
[[ 4.58  1.96  4.15  0.87]
 [ 0.    3.34  1.16  3.98]
 [ 0.   -0.    3.53  0.79]
 [-0.   -0.    0.    1.94]]
Check: A ≈ QR
[[3.98 1.   1.99 0.  ]
 [1.01 3.   0.99 1.99]
 [2.02 1.   5.01 0.99]
 [0.   2.   1.01 4.01]]

[[4. 1. 2. 0.]
 [1. 3. 1. 2.]
 [2. 1. 5. 1.]
 [0. 2. 1. 4.]]


The Givens method is numerically stable and efficient for symmetric or well-conditioned dense matrices due to fewer computational steps and better orthogonality preservation. In contrast, the Householder method is more stable and efficient for sparse or ill-conditioned matrices, offering improved numerical precision and reduced sensitivity to rounding errors, although it incurs higher computational costs for dense systems.

Task 5: Finding all eigenvalues using Jacobi's method.
Problem:
1. Using Jacobi's method, find all eigenvalues for the following matrix: Set the accuracy to 10
−6
.

Required:
1. Print the eigenvalues.
2. Compare the result with the numpy.linalg.eigvals function

In [ ]:
def jacobi_eigenvalues(A, tol, max_iter):
    """Jacobi's method for finding all eigenvalues."""
    n = A.shape[0]
    V = np.eye(n)
    for _ in range(max_iter):
        # Find the maximum off-diagonal element
        max_val = 0
        for i in range(n):
            for j in range(i+1, n):
                if abs(A[i, j]) > abs(max_val):
                    max_val = A[i, j]
                    p, q = i, j

        if abs(max_val) < tol:
            break

        # Calculating rotation parameters
        theta = 0.5 * np.arctan(2 * A[p, q] / (A[p, p] - A[q, q]))
        cos = np.cos(theta)
        sin = np.sin(theta)

        # We apply the Jacobi transformation
        R = np.eye(n)
        R[p, p] = R[q, q] = cos
        R[p, q] = sin
        R[q, p] = -sin
        A = R.T @ A @ R
        V = V @ R

    eigenvalues = np.diag(A)
    return eigenvalues

# Example of a symmetric matrix
A = np.array([[1, 1, 0.5], [1, 1, 0.25], [0.5, 0.25, 2]], dtype=float)

# Finding eigenvalues ​​and eigenvectors
eigenvalues1 = jacobi_eigenvalues(A, tol=1e-6, max_iter=100)
eigenvalues2 = np.linalg.eigvals(A)
print("Eigenvalues:")
print(eigenvalues1)
print("Eigenvalues with built-in function")
print(eigenvalues2[::-1])

Eigenvalues:
[ 1.47970688  2.53642885 -0.01613572]
Eigenvalues with built-in function
[ 1.48012142  2.53652586 -0.01664728]


<ipython-input-62-22d6a52fd17e>:19: RuntimeWarning: divide by zero encountered in scalar divide
  theta = 0.5 * np.arctan(2 * A[p, q] / (A[p, p] - A[q, q]))
